[package]
name = "gottlob_web"
version = "0.1.0"
authors = ["Jason Hills <jasonahills@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
custom_debug = "*"
gottlob = { path = "../gottlob" }
log = "*"
wasm-bindgen = "*"
wasm-logger = "*"
yew = "*"
