binary_op = _{ and | or | conditional | biconditional }
and = { "^" | " and " | "&" }
or = { "v" | " or " | "|" }
conditional = { "->" | " then " }
biconditional = { "<->" | " iff " }

negated = { ("~" | "not ") ~  ( grouped | negated | literal ) }
grouped = { "(" ~ expr ~ ")" }
term = { grouped | negated | literal }
literal = { 'a'..'u' | 'w'..'z' }

expr = { term ~ (binary_op ~ term)* }

whole_expr = _{ SOI ~ expr ~ EOI }

WHITESPACE = _{ " " | "\t" }